export type ArchiveEvent={id:string;title:string;titleEn:string;year:string;category:string;image:string;summary:string;speaker?:string;date:string;tags:string[]};

export const archiveImage=(event:ArchiveEvent)=>event.image.startsWith('/')?event.image:`/admin/assets/events/${event.image}`;

export const archiveEvents:ArchiveEvent[]=[
 {id:'cloud-computing',title:'مقدمة في الحوسبة السحابية',titleEn:'Introduction to Cloud Computing',year:'2020',category:'لقاء',image:'cloud-computing.webp',summary:'لقاء للتعرّف على الحوسبة السحابية والبنية التحتية التي تقوم عليها.',speaker:'د. عبدالعزيز الباتلي',date:'18 أكتوبر 2020',tags:['الحوسبة السحابية','البنية التحتية']},
 {id:'cryptographic-system',title:'كيف تكسر نظامًا للتشفير؟',titleEn:'How Do You Break a Cryptographic System?',year:'2020',category:'لقاء',image:'cryptographic-system.webp',summary:'لقاء تقني حول أنظمة التشفير والأمن السيبراني.',speaker:'د. علي الشهري',date:'21 أكتوبر 2020',tags:['التشفير','الأمن السيبراني']},
 {id:'high-performance-computing',title:'الحوسبة عالية الأداء للباحثين',titleEn:'High Performance Computing for Researchers',year:'2020',category:'ورشة',image:'high-performance-computing.webp',summary:'ورشة عن الحوسبة عالية الأداء واستخداماتها في البحث.',speaker:'هيفاء القاسم',date:'22 نوفمبر 2020',tags:['الحوسبة','البحث']},
 {id:'java-weekly-camp',title:'معسكر البرمجة الأسبوعي Java 1 وJava 2',titleEn:'Weekly Java 1 and Java 2 Camp',year:'2021',category:'معسكر',image:'java-weekly-camp.webp',summary:'مراجعة منتظمة وتمارين عملية لدعم فهم المفاهيم البرمجية وتطبيقها.',speaker:'عبدالرحمن العتيبي',date:'2021',tags:['Java','البرمجة']},
 {id:'game-storytelling',title:'ألعاب الفيديو: كتابة القصة والشخصية',titleEn:'Video Games: Story and Character Writing',year:'2021',category:'ورشة',image:'game-storytelling.webp',summary:'ورشة تستكشف كتابة القصة وتصميم الشخصيات في ألعاب الفيديو.',speaker:'غادة الجروان',date:'9 مارس 2021',tags:['ألعاب الفيديو','كتابة القصة']},
 {id:'electrical-engineering-collaboration',title:'تعاون نادي الهندسة الكهربائية',titleEn:'Electrical Engineering Club Collaboration',year:'2021',category:'تعاون',image:'electrical-engineering-collaboration.webp',summary:'التعاون الأول بين النادي ونادي الهندسة الكهربائية لإثراء الطلاب وتبادل المعرفة.',date:'أُعلن في 1 أكتوبر 2021',tags:['تعاون طلابي','الهندسة الكهربائية']},
 {id:'linux-administration',title:'إدارة أنظمة لينكس',titleEn:'Linux Systems Administration',year:'2021',category:'ورشة',image:'linux-administration.webp',summary:'تعرّف على لينكس وسطر الأوامر وإدارة المستخدمين والصلاحيات لبناء أساس في إدارة الأنظمة.',speaker:'م. عبدالمجيب الحميد',date:'16 أكتوبر 2021',tags:['Linux','سطر الأوامر']},
 {id:'solar-photovoltaics',title:'الطاقة الشمسية الكهروضوئية',titleEn:'Solar Photovoltaics',year:'2021',category:'ورشة',image:'solar-photovoltaics.webp',summary:'ورشة في الطاقة الشمسية الكهروضوئية والاستدامة.',speaker:'عبدالعزيز عبدالله الحربي',date:'13 نوفمبر 2021',tags:['الطاقة الشمسية','الاستدامة']},
 {id:'saudi-cpc',title:'المشاركة في Saudi CPC والتأهل للنهائيات',titleEn:'Saudi CPC Participation and Finals Qualification',year:'2022',category:'منافسة',image:'saudi-cpc.webp',summary:'مسار بدأ بالتعريف بالمسابقة وفرص التدريب، ووصل إلى تأهل أعضاء من النادي للنهائيات والمشاركة فيها.',date:'توثيق التأهل: 14 سبتمبر 2022',tags:['البرمجة التنافسية','حل المشكلات']},
 {id:'ieeextreme',title:'IEEEXtreme',titleEn:'IEEEXtreme',year:'2022',category:'منافسة',image:'/admin/assets/xtreme.webp',summary:'فرق الفرع تخوض تحديات برمجية متزامنة مع الفرق حول العالم، في تجربة لحل المشكلات والعمل الجماعي.',date:'أكتوبر 2022',tags:['البرمجة التنافسية','الخوارزميات']},
 {id:'python-data-analysis',title:'مقدمة في تحليل البيانات بالبايثون',titleEn:'Introduction to Data Analysis with Python',year:'2023',category:'ورشة',image:'python-data-analysis.webp',summary:'ورشة تعريفية بتحليل البيانات باستخدام لغة بايثون ومكتباتها.',speaker:'عمار حمدي حموش',date:'16 سبتمبر 2023',tags:['Python','تحليل البيانات']},
 {id:'after-graduation',title:'ما بعد التخرج',titleEn:'After Graduation',year:'2023',category:'لقاء',image:'after-graduation.webp',summary:'لقاء عن الاستعداد للمرحلة المهنية والاستفادة من تجربة ما بعد التخرج.',speaker:'دلال فهد',date:'21 أكتوبر 2023',tags:['المسار المهني','تجارب الخريجين']},
 {id:'ai-fundamentals',title:'أساسيات الذكاء الاصطناعي',titleEn:'Artificial Intelligence Fundamentals',year:'2024',category:'دورة',image:'ai-fundamentals.webp',summary:'مدخل للتعرّف على المفاهيم الأساسية للذكاء الاصطناعي.',speaker:'سارة السعدون',date:'26 أغسطس 2024',tags:['الذكاء الاصطناعي']},
 {id:'data-science-camp',title:'معسكر علم البيانات',titleEn:'Data Science Camp',year:'2024',category:'معسكر',image:'/admin/assets/data-detail.webp',summary:'تعلّم عملي باستخدام Python؛ من إدارة البيانات وتنظيفها إلى تحليلها بصريًا والتعرّف على تعلّم الآلة.',speaker:'أ. عبدالعزيز القحطاني',date:'سبتمبر 2024',tags:['Python','Pandas']},
 {id:'choose-your-major',title:'اختر مجالك بثقة',titleEn:'Choose Your Field with Confidence',year:'2024',category:'لقاء',image:'choose-your-major.webp',summary:'لقاء يربط اختيار المجال الدراسي بفهم الفرص المهنية ومتطلبات سوق العمل.',speaker:'م. عبدالمجيب الحميد',date:'2 سبتمبر 2024',tags:['المسار المهني','اختيار التخصص']},
 {id:'blockchain-fundamentals',title:'أساسيات البلوكتشين',titleEn:'Blockchain Fundamentals',year:'2024',category:'ورشة',image:'blockchain-fundamentals.webp',summary:'ورشة تأسيسية حول البلوكتشين والتشفير وتطبيقاتهما.',speaker:'الجوهرة الدوسري',date:'8 سبتمبر 2024',tags:['Blockchain','التشفير']},
 {id:'introduction-to-sql',title:'Introduction to SQL',titleEn:'Introduction to SQL',year:'2024',category:'ورشة',image:'introduction-to-sql.webp',summary:'تجربة تأسيسية للتعرّف على قواعد البيانات وإدارتها باستخدام SQL.',speaker:'ضحى الدوسري ووجد العمر',date:'9–11 سبتمبر 2024',tags:['SQL','قواعد البيانات']},
 {id:'network-engineer',title:'مسارك المهني كمهندس شبكات',titleEn:'Your Career Path as a Network Engineer',year:'2024',category:'لقاء',image:'network-engineer.webp',summary:'لقاء يستعرض المسار المهني في هندسة الشبكات.',speaker:'أ. خالد الخليفة',date:'25 سبتمبر 2024',tags:['الشبكات','المسار المهني']},
 {id:'artificial-intelligence-course',title:'الذكاء الاصطناعي',titleEn:'Artificial Intelligence',year:'2024',category:'دورة',image:'artificial-intelligence-course.webp',summary:'مصطلحات وخوارزميات وأدوات الذكاء الاصطناعي مع تطبيقات مبسّطة.',speaker:'سارة السعدون',date:'22 و25 ديسمبر 2024',tags:['الذكاء الاصطناعي','الخوارزميات']},
 {id:'augmented-reality-camp',title:'معسكر الواقع المعزز',titleEn:'Augmented Reality Camp',year:'2025',category:'معسكر',image:'/admin/assets/ar.webp',summary:'من استكشاف الميتافيرس إلى أدوات التصميم التفاعلي، وبناء مشاريع واقع معزز وعرضها أمام الحضور.',speaker:'فاطمة الدكان',date:'6–8 مايو 2025',tags:['الواقع المعزز','Lens Studio']},
 {id:'ccna-fundamentals',title:'أساسيات CCNA',titleEn:'CCNA Fundamentals',year:'2026',category:'ورشة',image:'ccna-fundamentals.webp',summary:'ورشة تقنية عن بُعد في أساسيات CCNA والشبكات.',speaker:'أحمد الأسمري',date:'نُشرت التغطية في 6 يونيو 2026',tags:['CCNA','الشبكات']},
 {id:'arduino-fundamentals',title:'أساسيات الأردوينو',titleEn:'Arduino Fundamentals',year:'2026',category:'ورشة',image:'arduino-fundamentals.webp',summary:'ورشة تقنية عن بُعد في أساسيات الأردوينو.',speaker:'خالد المقبل',date:'نُشرت التغطية في 6 يونيو 2026',tags:['Arduino','الإلكترونيات']},
 {id:'devfest',title:'مشاركة النادي في DevFest',titleEn:'IEEE IMSIU at DevFest',year:'2024',category:'مشاركة',image:'/admin/assets/devfest.webp',summary:'ركن تقني لتبادل المعرفة واستكشاف الويب الحديث والبلوكتشين والميتافيرس ومكتبة IEEE.',date:'1 يناير 2024',tags:['DevFest','Web3','مجتمع تقني']},
 {id:'emerging-technologies',title:'آفاق التقنيات الحديثة',titleEn:'Emerging Technology Horizons',year:'2024',category:'لقاء',image:'emerging-technologies.webp',summary:'لقاء يقرّب مفاهيم الويب الحديث والبلوكتشين والميتافيرس وتطبيقاتها من المجتمع الطلابي.',speaker:'رغد عبدالغني',date:'1 يناير 2024',tags:['Web3','Blockchain']},
 {id:'community-visit',title:'زيارة جمعية الأطفال ذوي الإعاقة',titleEn:'Children with Disability Association Visit',year:'2024',category:'زيارة',image:'/admin/assets/volunteer.webp',summary:'زيارة تطوعية بمناسبة اليوم الوطني السعودي، تعزّز المشاركة المجتمعية وثقافة التطوع.',date:'1 أكتوبر 2024',tags:['التطوع','المشاركة المجتمعية']},
 {id:'introduction-data-science',title:'مدخل إلى علم وتحليل البيانات',titleEn:'Introduction to Data Science and Analysis',year:'2026',category:'ورشة',image:'introduction-data-science.webp',summary:'ورشة تقنية عن بُعد للتعرّف على علم البيانات وتحليلها.',speaker:'عبدالرحمن الخليفي',date:'25 أبريل 2026',tags:['علم البيانات','تحليل البيانات']}
];
