import {HttpError} from './auth';
import type {Row} from './domain';
import type {RuntimeEnv} from './runtime-env';
export async function verifyTurnstile(env:RuntimeEnv,request:Request,token:string){
 if(env.APP_ENV==='development'&&['127.0.0.1','localhost','[::1]'].includes(new URL(request.url).hostname))return;
 if(!env.TURNSTILE_SECRET||!token)throw new HttpError(422,'أكمل التحقق الأمني.');
 const form=new FormData();form.set('secret',env.TURNSTILE_SECRET);form.set('response',token);form.set('remoteip',request.headers.get('CF-Connecting-IP')||'');
 const result=await fetch('https://challenges.cloudflare.com/turnstile/v0/siteverify',{method:'POST',body:form}).then(r=>r.json() as Promise<{success:boolean}>);if(!result.success)throw new HttpError(422,'تعذر التحقق الأمني. حاول مجددًا.');
}
export async function rateLimit(env:Env,key:string,limit:number,seconds:number){const now=Math.floor(Date.now()/1000),result=await env.DB.prepare('INSERT INTO rate_limits(key,hits,expires) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET hits=CASE WHEN expires<? THEN 1 ELSE hits+1 END,expires=CASE WHEN expires<? THEN excluded.expires ELSE expires END RETURNING hits').bind(key,now+seconds,now,now).first<{hits:number}>();if(!result||result.hits>limit)throw new HttpError(429,'محاولات كثيرة. حاول لاحقًا.');}
export function readDynamicFields(fields:unknown,values:Record<string,unknown>){if(!Array.isArray(fields))throw new HttpError(422,'نموذج التسجيل غير صالح.');const answers:Record<string,string|string[]>={};for(let i=0;i<fields.length;i++){const field=fields[i] as Record<string,unknown>,key=String(i),value=values[key];if(field.required&&(value===undefined||value===''||Array.isArray(value)&&!value.length))throw new HttpError(422,`الحقل «${field.label}» مطلوب.`);if(value===undefined||value==='')continue;if(typeof value!=='string'&&!Array.isArray(value))throw new HttpError(422,'إجابة غير صالحة.');const parts=Array.isArray(value)?value:[value];if(parts.some(v=>typeof v!=='string'||v.length>2000))throw new HttpError(422,'الإجابة أطول من المسموح.');if(field.type==='email'&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(value)))throw new HttpError(422,'البريد الإلكتروني غير صالح.');answers[key]=value as string|string[];}if(Object.keys(values).some(k=>!/^\d+$/.test(k)||Number(k)>=fields.length))throw new HttpError(422,'يحتوي الطلب على حقول غير معروفة.');return answers;}
export function personFromAnswers(fields:unknown,answers:Record<string,string|string[]>){const list=fields as Row[],take=(types:string[],labels:RegExp)=>{let i=list.findIndex(x=>labels.test(String(x.label)));if(i<0)i=list.findIndex(x=>types.includes(String(x.type)));return typeof answers[String(i)]==='string'?String(answers[String(i)]):'';};return {name:take(['text'],/الاسم|name/i),email:take(['email'],/البريد|email/i).trim().toLowerCase(),phone:take(['tel'],/الجوال|phone/i),studentId:take(['number'],/الجامعي|student/i),major:take([],/التخصص|major/i)};}
