import assert from 'node:assert/strict';
import {chromium} from 'playwright';
const origin=process.env.TEST_ORIGIN||'http://127.0.0.1:4321';
const browser=await chromium.launch({channel:'chrome',headless:true});
try{
 const context=await browser.newContext({locale:'ar-SA',extraHTTPHeaders:{'X-Dev-Email':'admin@example.test'}}),page=await context.newPage(),errors=[];
 page.setDefaultTimeout(25000);page.on('console',message=>{if(message.type()==='error')errors.push(message.text());});page.on('pageerror',error=>errors.push(error.message));
 await page.goto(origin+'/',{waitUntil:'domcontentloaded'});
 assert.match(await page.locator('h1').first().innerText(),/فضولك التقني/);assert.equal(await page.locator('html').getAttribute('dir'),'rtl');assert.match(await page.locator('h1').first().evaluate(element=>getComputedStyle(element).fontFamily),/Vazirmatn/);
 assert.ok((await page.locator('.site-header .brand').boundingBox()).width>=200);assert.equal(await page.locator('.partner-logo').count(),18);assert.equal(await page.locator('.social-links a').count(),4);
 await page.locator('.legacy-metrics').first().evaluate(element=>element.scrollIntoView({block:'center'}));await page.waitForFunction(()=>document.querySelectorAll('[data-counted="true"]').length>=2);await page.waitForFunction(()=>document.querySelector('[data-count="3216"]')?.textContent==='3,216+');
 const navBox=await page.locator('#site-nav').boundingBox();assert.ok(Math.abs(navBox.x+navBox.width/2-640)<90);
 await page.locator('[data-theme-toggle]').click({force:true});assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');assert.equal(await page.locator('.site-header .brand-color').isVisible(),false);assert.equal(await page.locator('.site-header .brand-white').isVisible(),true);
 await page.goto(origin+'/events',{waitUntil:'domcontentloaded'});assert.equal(await page.locator('.card').count(),0);assert.equal(await page.locator('.empty').isVisible(),true);
 await page.goto(origin+'/events/archive',{waitUntil:'domcontentloaded'});assert.equal(await page.locator('.archive-card').count(),26);assert.equal(await page.getByText('أنشطة غير مؤرخة').count(),0);assert.equal(await page.getByText('من أنشطة النادي').count(),0);assert.ok(await page.getByText('1 يناير 2024',{exact:true}).count()>=2);assert.equal(await page.getByText('25 أبريل 2026').count(),1);assert.ok(await page.locator('.archive-card img').first().evaluate(image=>image.naturalWidth>0));assert.match(await page.locator('.archive-card').first().innerText(),/18 أكتوبر 2020/);await page.locator('.archive-card').first().click();assert.equal(await page.locator('.event-facts dd').first().textContent(),'د. عبدالعزيز الباتلي');assert.equal(await page.getByText('انتهت الفعالية').count(),0);
 await page.goto(origin+'/collaboration',{waitUntil:'domcontentloaded'});assert.equal(await page.locator('.collaboration-contact img').count(),0);const slider=page.locator('.partner-logos');const drag=await slider.evaluate(async element=>{element.scrollIntoView({block:'center'});element.scrollLeft=element.scrollWidth/2;element.setPointerCapture=()=>{};element.hasPointerCapture=()=>false;const send=(type,x)=>element.dispatchEvent(new PointerEvent(type,{pointerId:1,button:0,clientX:x,bubbles:true,cancelable:true})),before=element.scrollLeft;send('pointerdown',200);send('pointermove',100);const after=element.scrollLeft;send('pointerup',100);await new Promise(resolve=>setTimeout(resolve,500));return{before,after,glided:element.scrollLeft};});assert.notEqual(drag.after,drag.before);assert.ok(Math.abs(drag.glided-drag.before)>Math.abs(drag.after-drag.before));
 await page.locator('[data-lang-toggle]').click();await page.goto(origin+'/impact',{waitUntil:'domcontentloaded'});assert.equal(await page.locator('html').getAttribute('lang'),'en');assert.equal(await page.locator('html').getAttribute('dir'),'ltr');assert.equal(await page.locator('nav a[href="/impact"]').textContent(),'Impact');assert.match(await page.locator('h1').innerText(),/Impact made/);assert.equal(await page.locator('.site-header .brand-white').isVisible(),true);
 await page.locator('[data-lang-toggle]').click();assert.equal(await page.locator('html').getAttribute('lang'),'ar');assert.match(await page.locator('h1').innerText(),/أثر تصنعه/);
 await page.goto(origin+'/admin',{waitUntil:'commit'});await page.locator('h1').first().waitFor();assert.equal(await page.locator('h1').first().textContent(),'الرئيسية');assert.equal(await page.locator('.preview-strip:visible').count(),0);assert.ok((await page.locator('.account').textContent()).includes('admin@example.test'));
 await page.setViewportSize({width:390,height:844});assert.equal(await page.locator('.mobile-menu').isVisible(),true);assert.deepEqual(errors,[]);
 console.log('PASS: public identity, archive, 12-hour time, preferences, and responsive administration render without browser errors');
}finally{await browser.close();}
