import type {APIRoute} from 'astro';
import {env} from 'cloudflare:workers';
import {z} from 'zod';
import {Resend} from 'resend';
import {commit,readState} from '../../../lib/db';
import {failure,HttpError,identity,jsonBody,respond,sameOrigin} from '../../../lib/auth';
import type {RuntimeEnv} from '../../../lib/runtime-env';
const schema=z.object({id:z.uuid(),subject:z.string().trim().min(1).max(180),body:z.string().trim().min(1).max(10000),link:z.union([z.literal(''),z.url().refine(v=>/^https?:/.test(v))]),button:z.string().max(100),banner:z.union([z.literal(''),z.string().regex(/^\/media\/[\w-]+$/)]),recipients:z.array(z.string().min(1).max(100)).min(1).max(100)});
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export const POST:APIRoute=async({request})=>{try{sameOrigin(request);const runtimeEnv:RuntimeEnv=env;const user=await identity(request,env);if(user.role==='editor')throw new HttpError(403,'لا تملك صلاحية إرسال هذه الرسائل.');if(!runtimeEnv.RESEND_API_KEY||!runtimeEnv.EMAIL_FROM)throw new HttpError(503,'أضف إعدادات Resend وعنوان المرسل قبل الإرسال.');const input=schema.parse(await jsonBody(request,100000));const existing=await env.DB.prepare("SELECT payload FROM records WHERE kind='dispatches' AND id=?").bind(input.id).first<{payload:string}>();if(existing)return respond({id:input.id});
 const placeholders=input.recipients.map(()=>'?').join(','),rows=await env.DB.prepare(`SELECT payload FROM records WHERE kind IN ('registrations','applications','members') AND id IN (${placeholders})`).bind(...input.recipients).all<{payload:string}>(),people=rows.results.map(x=>JSON.parse(x.payload) as {id:string;name:string;email:string});if(new Set(people.map(x=>x.id)).size!==new Set(input.recipients).size)throw new HttpError(422,'تعذر العثور على بعض المستلمين.');
 const html=(name:string)=>`<!doctype html><html lang="ar" dir="rtl"><body style="font-family:Arial,sans-serif;color:#1c2e40"><div style="max-width:620px;margin:auto">${input.banner?`<img src="${new URL(input.banner,request.url)}" alt="" style="max-width:100%;height:auto">`:''}<h1 style="color:#2f6d9e">${esc(input.subject)}</h1>${input.body.split(/\n+/).map(p=>`<p>${esc(p.replaceAll('{name}',name))}</p>`).join('')}${input.link?`<p><a style="background:#2f6d9e;color:#fff;padding:12px 18px;text-decoration:none" href="${esc(input.link)}">${esc(input.button||'عرض التفاصيل')}</a></p>`:''}<p style="color:#607184">IEEE IMSIU</p></div></body></html>`;
 const resend=new Resend(runtimeEnv.RESEND_API_KEY),result=await resend.batch.send(people.map(p=>({from:runtimeEnv.EMAIL_FROM,to:[p.email],subject:input.subject,html:html(p.name)})),{idempotencyKey:input.id});if(result.error)throw new HttpError(502,'رفض مزود البريد عملية الإرسال. راجع إعدادات النطاق.');const ids=(result.data?.data||[]).map(x=>x.id),dispatch={id:input.id,subject:input.subject,body:input.body,link:input.link,button:input.button,date:new Date().toISOString().slice(0,10),recipients:people.map((p,i)=>({...p,providerId:ids[i],status:'Sent'}))};
 for(let attempt=0;attempt<3;attempt++){const {version}=await readState(env.DB);try{await commit(env.DB,version,user.email,[{kind:'dispatches',id:input.id,value:dispatch}]);return respond({id:input.id},201);}catch(error){if(!/UNIQUE constraint failed: revisions.version/.test(error instanceof Error?error.message:''))throw error;}}
 throw new HttpError(409,'تم الإرسال، وتعذر حفظ النتيجة مؤقتًا. أعد المحاولة بنفس الرسالة.');
 }catch(error){if(error instanceof z.ZodError)return respond({error:'راجع محتوى الرسالة والمستلمين.'},422);return failure(error);}};
