/// <reference types="astro/client" />
// Secret names are optional until deployment; binding types are generated by Wrangler.
interface Env { RESEND_API_KEY?:string; TURNSTILE_SECRET?:string; RESEND_WEBHOOK_SECRET?:string; }
